version: "3"
services:
    renameD:
        image: "prod/renamed:18.10.17"
        environment:
            - LOCAL_USER_ID=1000
        volumes:
            - ~/ws/renameD/src:/home/user/src
#            - internal:/mnt/source
            - source:/mnt/src
            - destination:/mnt/dst
              #- ~/ws/renameD/mount/source:/mnt/source
              #- ~/ws/renameD/mount/destination:/mnt/destination
              #            - volume-Vault6-out:/mnt/destination
        command: "python3 /usr/local/bin/renameD.py --src /mnt/src --dst /mnt/dst"
        user: root
        container_name: "RenameDaemon"

        stdin_open: true
        tty: true

    inotify:
        image: "local/renamed:18.10.17"
        environment:
            - LOCAL_USER_ID=1000
        volumes:
            - ~/ws/renameD/src:/home/user/src
            - ~/ws/renameD/test:/home/user/test
            - ~/ws/renameD/mount:/home/user/mount
        command: "python3 /home/user/src/inotify_test.py"
        user: root
        container_name: "RenameDaemonInotify"

        stdin_open: true
        tty: true


    tests:
        image: "local/renamed:18.10.17"
        environment:
            - LOCAL_USER_ID=1000
        volumes:
            - ~/ws/renameD/src:/home/user/src
            - ~/ws/renameD/test:/home/user/test
        command: "pytest -s /home/user/test/"
        user: root
        container_name: "RenameDaemonTest"

        stdin_open: true
        tty: true

volumes:
    source:
        driver: cifs
        driver_opts:
            share: drusus.local/Vault6/Drive/Incoming
    destination:
        driver: cifs
        driver_opts:
            share: drusus.local/Vault6/Drive/Outgoing
